# Generated by Django 2.2.6 on 2019-10-24 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Man',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('date_of_born', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('date_of_production', models.DateField()),
                ('genre', models.CharField(choices=[('cy', 'Comedy'), ('de', 'Action'), ('ae', 'Adventure'), ('ce', 'Crime'), ('da', 'Drama'), ('fy', 'Fantasy'), ('hl', 'Historical'), ('hr', 'Horror')], max_length=2)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='played_films', to='api.Man')),
                ('producer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produced_films', to='api.Man')),
            ],
        ),
    ]
